[tox]
envlist =
    pycodestyle
    django52-py{310,311,312,313}
    django60-py{312,313}

[testenv]
deps =
    coverage
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    pycodestyle: pycodestyle
commands =
    !pycodestyle: coverage run manage.py test
    pycodestyle: pycodestyle markdown_view/

[pycodestyle]
max-line-length = 99
